import { useState, useRef, useEffect } from "react";

const DAY_NAMES = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

function calcH(start, end) {
  const s = parseFloat(start), e = parseFloat(end);
  if (isNaN(s) || isNaN(e) || e < s) return null;
  return parseFloat((e - s).toFixed(2));
}

function billHours(h) {
  if (h === null) return null;
  const mins = Math.round((h - Math.floor(h)) * 60);
  return mins >= 30 ? Math.ceil(h) : Math.floor(h);
}

function fmt(h) {
  if (h === null || h === undefined) return "—";
  const hrs = Math.floor(h);
  const mins = Math.round((h - hrs) * 60);
  return mins > 0 ? (hrs + "h " + mins + "m") : (hrs + "h");
}

function getDays(start, end) {
  const days = [], cur = new Date(start), last = new Date(end);
  while (cur <= last) { days.push(new Date(cur)); cur.setDate(cur.getDate() + 1); }
  return days;
}

function fmtDate(d, opts) { return d.toLocaleDateString("en-GB", opts); }
function emptyRow() { return { dayStart: "", dayEnd: "", nightStart: "", nightEnd: "", noWork: false, reason: "" }; }

function buildReportHTML(reportText, meta) {
  const body = reportText
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>\n?)+/g, function(m) { return "<ul>" + m + "</ul>"; })
    .replace(/\n\n/g, "</p><p>").replace(/\n/g, "<br/>");
  return "<!DOCTYPE html><html><head><meta charset='utf-8'/><title>" + meta.title + "</title><style>" +
    "body{font-family:Georgia,serif;max-width:800px;margin:40px auto;padding:0 32px;color:#111;font-size:14px;line-height:1.8}" +
    "h1{font-size:22px;margin:0 0 4px}" +
    "h2{font-size:17px;font-weight:600;margin:2rem 0 0.5rem;border-bottom:1px solid #ddd;padding-bottom:4px}" +
    "h3{font-size:14px;font-weight:600;margin:1.25rem 0 0.25rem;color:#333}" +
    "ul{margin:0.25rem 0 0.5rem 1.25rem;padding:0}" +
    "li{margin:0.15rem 0}" +
    "p{margin:0.4rem 0}" +
    ".meta{font-size:13px;color:#555;margin-bottom:1.5rem}" +
    ".header{border-bottom:2px solid #111;padding-bottom:12px;margin-bottom:24px}" +
    ".badge{display:inline-block;background:#f3f3f3;border:1px solid #ddd;border-radius:4px;padding:2px 10px;font-size:12px;margin-right:8px}" +
    "@media print{body{margin:20px auto}}" +
    "</style></head><body>" +
    "<div class='header'><h1>" + meta.machineName + "</h1>" +
    "<div class='meta'>" +
    "<span class='badge'>📅 " + meta.period + "</span>" +
    "<span class='badge'>⏱ " + meta.totalHours + "h total</span>" +
    "<span class='badge'>" + meta.weeks + " week" + (meta.weeks !== 1 ? "s" : "") + "</span>" +
    (meta.noWorkDays > 0 ? "<span class='badge'>⛔ " + meta.noWorkDays + " no-work day" + (meta.noWorkDays !== 1 ? "s" : "") + "</span>" : "") +
    "</div></div>" +
    "<p>" + body + "</p>" +
    "<div style='margin-top:40px;padding-top:12px;border-top:1px solid #ddd;font-size:11px;color:#999'>Generated by Machine Hours Tracker · " + new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }) + "</div>" +
    "</body></html>";
}

function downloadPDF(reportText, meta) {
  const html = buildReportHTML(reportText, meta);
  const w = window.open("", "_blank");
  if (!w) { alert("Please allow pop-ups to download the report."); return; }
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(function() { w.print(); }, 400);
}

function downloadImage(reportText, meta, callback) {
  const html = buildReportHTML(reportText, meta);
  const W = 860, H = 1200;
  const svg = "<svg xmlns='http://www.w3.org/2000/svg' width='" + W + "' height='" + H + "'>" +
    "<foreignObject width='100%' height='100%'>" +
    "<div xmlns='http://www.w3.org/1999/xhtml' style='background:#fff;padding:0;margin:0;width:" + W + "px;min-height:" + H + "px'>" +
    html.replace(/<html>|<\/html>|<!DOCTYPE html>/gi, "").replace(/<head>[\s\S]*?<\/head>/i, "") + "</div></foreignObject></svg>";
  const blob = new Blob([svg], { type: "image/svg+xml;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const img = new Image();
  img.onload = function() {
    const canvas = document.createElement("canvas");
    canvas.width = W; canvas.height = H;
    const ctx = canvas.getContext("2d");
    ctx.fillStyle = "#fff"; ctx.fillRect(0, 0, W, H);
    ctx.drawImage(img, 0, 0);
    URL.revokeObjectURL(url);
    const a = document.createElement("a");
    a.download = meta.machineName.replace(/\s+/g, "_") + "_report.png";
    a.href = canvas.toDataURL("image/png");
    a.click();
    if (callback) callback();
  };
  img.onerror = function() {
    URL.revokeObjectURL(url);
    alert("Image export failed. Try PDF instead.");
    if (callback) callback();
  };
  img.src = url;
}

function DownloadButtons(props) {
  const [imgLoading, setImgLoading] = useState(false);
  const meta = {
    machineName: props.machineName,
    period: props.period,
    totalHours: props.totalHours,
    weeks: props.weeks,
    noWorkDays: props.noWorkDays,
    title: props.machineName + " — Machine Hours Report"
  };
  return (
    <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
      <button onClick={function() { downloadPDF(props.report, meta); }}
        style={{ fontSize: 13, padding: "6px 14px", display: "flex", alignItems: "center", gap: 6 }}>
        ⬇ Download PDF
      </button>
      <button onClick={function() {
        setImgLoading(true);
        downloadImage(props.report, meta, function() { setImgLoading(false); });
      }} disabled={imgLoading}
        style={{ fontSize: 13, padding: "6px 14px", display: "flex", alignItems: "center", gap: 6 }}>
        {imgLoading ? "Exporting..." : "🖼 Save as Image"}
      </button>
    </div>
  );
}

function renderMarkdown(t) {
  return t
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/^### (.+)$/gm, "<h3 style=\"font-size:14px;font-weight:600;margin:1.1rem 0 0.3rem;color:var(--color-text-primary)\">$1</h3>")
    .replace(/^## (.+)$/gm, "<h2 style=\"font-size:16px;font-weight:600;margin:1.5rem 0 0.5rem;color:var(--color-text-primary);border-bottom:1px solid var(--color-border-tertiary);padding-bottom:4px\">$1</h2>")
    .replace(/^- (.+)$/gm, "<div style=\"margin:0.2rem 0;padding-left:1rem;color:var(--color-text-primary)\"><span style=\"color:var(--color-text-secondary);margin-right:6px\">•</span>$1</div>")
    .replace(/\n\n/g, "<br/>").replace(/\n/g, " ");
}

export default function App() {
  const [view, setView] = useState("home"); // home | tracker | history | historyDetail
  const [step, setStep] = useState(1);
  const [machineName, setMachineName] = useState("");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [days, setDays] = useState([]);
  const [rows, setRows] = useState([]);
  const [report, setReport] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [history, setHistory] = useState([]);
  const [selectedEntry, setSelectedEntry] = useState(null);
  const [historyLoading, setHistoryLoading] = useState(false);
  const reportRef = useRef(null);

  useEffect(function() { loadHistory(); }, []);

  async function loadHistory() {
    setHistoryLoading(true);
    try {
      const result = await window.storage.list("mht:");
      if (result && result.keys && result.keys.length > 0) {
        const entries = [];
        for (let i = 0; i < result.keys.length; i++) {
          try {
            const r = await window.storage.get(result.keys[i]);
            if (r) entries.push(JSON.parse(r.value));
          } catch (e) {}
        }
        entries.sort(function(a, b) { return b.savedAt - a.savedAt; });
        setHistory(entries);
      }
    } catch (e) {}
    setHistoryLoading(false);
  }

  async function saveToHistory(entry) {
    const key = "mht:" + entry.id;
    try {
      await window.storage.set(key, JSON.stringify(entry));
      setHistory(function(prev) {
        const next = [entry].concat(prev.filter(function(e) { return e.id !== entry.id; }));
        return next;
      });
    } catch (e) {}
  }

  async function deleteEntry(id) {
    try {
      await window.storage.delete("mht:" + id);
      setHistory(function(prev) { return prev.filter(function(e) { return e.id !== id; }); });
      if (selectedEntry && selectedEntry.id === id) { setSelectedEntry(null); setView("history"); }
    } catch (e) {}
  }

  const dateError = (startDate && endDate && new Date(endDate) < new Date(startDate)) ? "End date must be after start date." : null;
  const dayCount = (startDate && endDate && !dateError) ? getDays(startDate, endDate).length : 0;
  const tooMany = dayCount > 31;

  function handleProceed() {
    const d = getDays(startDate, endDate);
    setDays(d); setRows(d.map(emptyRow));
    setReport(""); setSubmitted(false); setError(""); setStep(2);
  }

  function setField(i, field, val) {
    setRows(function(prev) {
      return prev.map(function(r, idx) {
        if (idx !== i) return r;
        const next = Object.assign({}, r);
        next[field] = val.replace(/[^0-9.]/g, "");
        return next;
      });
    });
  }

  function toggleNoWork(i) {
    setRows(function(prev) {
      return prev.map(function(r, idx) {
        if (idx !== i) return r;
        return Object.assign({}, r, { noWork: !r.noWork, dayStart: "", dayEnd: "", nightStart: "", nightEnd: "" });
      });
    });
  }

  function setReason(i, val) {
    setRows(function(prev) {
      return prev.map(function(r, idx) {
        if (idx !== i) return r;
        return Object.assign({}, r, { reason: val });
      });
    });
  }

  const dayHours = rows.map(function(r) { return r.noWork ? null : calcH(r.dayStart, r.dayEnd); });
  const nightHours = rows.map(function(r) { return r.noWork ? null : calcH(r.nightStart, r.nightEnd); });
  const dayBilled = dayHours.map(billHours);
  const nightBilled = nightHours.map(billHours);

  const totalPerDay = dayHours.map(function(d, i) {
    const n = nightHours[i];
    if (d === null && n === null) return null;
    return parseFloat(((d || 0) + (n || 0)).toFixed(2));
  });

  const filledDays = totalPerDay.filter(function(h) { return h !== null; });
  const canGenerate = filledDays.length >= 1 || rows.some(function(r) { return r.noWork; });
  const grandTotal = filledDays.reduce(function(a, b) { return a + b; }, 0);
  const avg = filledDays.length ? grandTotal / filledDays.length : 0;
  const validTotals = totalPerDay.filter(function(h) { return h !== null; });
  const peak = validTotals.length ? Math.max.apply(null, validTotals) : 0;
  const low = validTotals.length ? Math.min.apply(null, validTotals) : 0;
  const peakIdx = totalPerDay.indexOf(peak);
  const peakDayLabel = days[peakIdx] ? fmtDate(days[peakIdx], { day: "numeric", month: "short" }) : "—";
  const maxBar = Math.max.apply(null, totalPerDay.map(function(h) { return h || 0; }).concat([1]));

  function hasErr(i, shift) {
    const s = parseFloat(rows[i][shift + "Start"]);
    const e = parseFloat(rows[i][shift + "End"]);
    return rows[i][shift + "Start"] && rows[i][shift + "End"] && !isNaN(s) && !isNaN(e) && e < s;
  }

  function inputSm(err) {
    return { width: "100%", boxSizing: "border-box", fontSize: 13, borderColor: err ? "var(--color-border-danger)" : undefined };
  }

  async function generateReport() {
    setLoading(true); setError(""); setReport(""); setSubmitted(true);
    setTimeout(function() { if (reportRef.current) reportRef.current.scrollIntoView({ behavior: "smooth" }); }, 100);

    const weekGroups = [];
    for (let wi = 0; wi < days.length; wi += 6) {
      const grp = [];
      for (let wj = wi; wj < Math.min(wi + 6, days.length); wj++) grp.push(wj);
      weekGroups.push(grp);
    }

    const dailyLines = days.map(function(d, i) {
      const dateStr = fmtDate(d, { weekday: "long", day: "numeric", month: "long", year: "numeric" });
      if (rows[i].noWork) return dateStr + " | NO WORK — Reason: " + (rows[i].reason || "No reason given");
      const dh = dayHours[i], nh = nightHours[i];
      const db = dayBilled[i], nb = nightBilled[i];
      const dl = dh !== null ? ("Day Shift: StartOdo=" + rows[i].dayStart + " EndOdo=" + rows[i].dayEnd + " Actual=" + dh.toFixed(2) + "h Billed=" + db + "h") : "Day Shift: no data";
      const nl = nh !== null ? ("Night Shift: StartOdo=" + rows[i].nightStart + " EndOdo=" + rows[i].nightEnd + " Actual=" + nh.toFixed(2) + "h Billed=" + nb + "h") : "Night Shift: no data";
      return dateStr + " | " + dl + " | " + nl;
    }).join("\n");

    const weeklyLines = weekGroups.map(function(idxs, w) {
      const wS = fmtDate(days[idxs[0]], { weekday: "short", day: "numeric", month: "short" });
      const wE = fmtDate(days[idxs[idxs.length - 1]], { weekday: "short", day: "numeric", month: "short" });
      const dayEntries = idxs.map(function(i) {
        if (rows[i].noWork) return fmtDate(days[i], { weekday: "short", day: "numeric", month: "short" }) + ": NO WORK (" + (rows[i].reason || "no reason") + ")";
        const db = dayBilled[i];
        return fmtDate(days[i], { weekday: "short", day: "numeric", month: "short" }) + ": " + (db !== null ? db + "h" : "no data");
      }).join(", ");
      const nightEntries = idxs.map(function(i) {
        if (rows[i].noWork) return fmtDate(days[i], { weekday: "short", day: "numeric", month: "short" }) + ": NO WORK";
        const nb = nightBilled[i];
        return fmtDate(days[i], { weekday: "short", day: "numeric", month: "short" }) + ": " + (nb !== null ? nb + "h" : "no data");
      }).join(", ");
      const wDB = idxs.reduce(function(s, i) { return s + (dayBilled[i] || 0); }, 0);
      const wNB = idxs.reduce(function(s, i) { return s + (nightBilled[i] || 0); }, 0);
      return "Week " + (w + 1) + " (" + wS + " to " + wE + "):\n  Day shifts: " + dayEntries + "\n  Total Day Shift: " + wDB + "h\n  Night shifts: " + nightEntries + "\n  Total Night Shift: " + wNB + "h\n  Total Week: " + wDB + "h + " + wNB + "h = " + (wDB + wNB) + "h";
    }).join("\n\n");

    const periodStart = fmtDate(days[0], { weekday: "long", day: "numeric", month: "long", year: "numeric" });
    const periodEnd = fmtDate(days[days.length - 1], { weekday: "long", day: "numeric", month: "long", year: "numeric" });
    const prompt = [
      "You are an industrial equipment analyst. Generate a structured professional operations report.",
      "Machine: " + (machineName || "Unnamed Machine"),
      "Period: " + periodStart + " to " + periodEnd,
      "Note: A week = 6 days. Less than 30 mins rounds down, 30+ rounds up.",
      "", "DAILY DATA:", dailyLines, "", "WEEKLY DATA:", weeklyLines, "",
      "Generate the report in this EXACT structure:",
      "", "## Daily Report", "",
      "For EACH day:", "### [Full date]",
      "**Day Shift**", "- Start Odometer: [value]", "- End Odometer: [value]", "- Actual Hours: [value]h", "- Billed Hours: [value]h",
      "", "**Night Shift**", "- Start Odometer: [value]", "- End Odometer: [value]", "- Actual Hours: [value]h", "- Billed Hours: [value]h",
      "If no data: No data recorded. If NO WORK: NO WORK — Reason: [reason]",
      "", "## Weekly Report", "",
      "For EACH week:", "### Week [N] ([start] to [end])", "",
      "**Day Shifts**", "- [Date]: [billed]h (or NO WORK — [reason])", "...", "**Total Day Shift: [X]h**", "",
      "**Night Shifts**", "- [Date]: [billed]h (or NO WORK)", "...", "**Total Night Shift: [X]h**", "",
      "**Total Week: [day]h + [night]h = [combined]h**", "",
      "## Overall Summary", "3-4 sentences on performance, no-work days, trends, and 2 recommendations.",
      "Use only the data provided. Be precise and professional."
    ].join("\n");

    try {
      const res = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ model: "claude-sonnet-4-5", max_tokens: 1200, messages: [{ role: "user", content: prompt }] })
      });
      const data = await res.json();
      if (!res.ok) { setError("API error " + res.status + ": " + (data.error ? data.error.message : "Unknown error")); setLoading(false); return; }
      const text = (data.content || []).map(function(b) { return b.text || ""; }).join("");
      setReport(text || "No report generated.");

      // Save to history
      const entry = {
        id: Date.now().toString(),
        savedAt: Date.now(),
        machineName: machineName || "Unnamed Machine",
        startDate: startDate,
        endDate: endDate,
        totalHours: grandTotal.toFixed(2),
        weeks: Math.ceil(days.length / 6),
        noWorkDays: rows.filter(function(r) { return r.noWork; }).length,
        report: text
      };
      await saveToHistory(entry);
    } catch (e) {
      setError("Request failed: " + e.message);
    }
    setLoading(false);
  }

  // ── HOME / NAV ──
  function NavBar() {
    return (
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "1.5rem" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <span style={{ fontSize: 18, fontWeight: 600, color: "var(--color-text-primary)", cursor: "pointer" }} onClick={function() { setView("home"); }}>⚙ MHT</span>
        </div>
        <div style={{ display: "flex", gap: 8 }}>
          <button onClick={function() { setView("tracker"); setStep(1); }} style={{ fontSize: 13, padding: "6px 14px", background: view === "tracker" ? "var(--color-background-active)" : "var(--color-background-secondary)" }}>
            + New Report
          </button>
          <button onClick={function() { setView("history"); loadHistory(); }} style={{ fontSize: 13, padding: "6px 14px", background: view === "history" || view === "historyDetail" ? "var(--color-background-active)" : "var(--color-background-secondary)" }}>
            History {history.length > 0 ? "(" + history.length + ")" : ""}
          </button>
        </div>
      </div>
    );
  }

  // ── HISTORY VIEW ──
  if (view === "history") {
    return (
      <div style={{ padding: "1.5rem 1rem", maxWidth: 680, margin: "0 auto", fontFamily: "var(--font-sans)" }}>
        <NavBar />
        <h2 style={{ fontSize: 18, fontWeight: 500, margin: "0 0 1rem", color: "var(--color-text-primary)" }}>Report History</h2>
        {historyLoading && <p style={{ color: "var(--color-text-secondary)", fontSize: 14 }}>Loading history...</p>}
        {!historyLoading && history.length === 0 && (
          <div style={{ textAlign: "center", padding: "3rem 0", color: "var(--color-text-tertiary)", fontSize: 14 }}>
            <div style={{ fontSize: 32, marginBottom: 12 }}>📋</div>
            No reports saved yet. Generate your first report!
          </div>
        )}
        {history.map(function(entry) {
          const d = new Date(entry.savedAt);
          const savedStr = d.toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" }) + " at " + d.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" });
          return (
            <div key={entry.id} style={{ background: "var(--color-background-primary)", border: "0.5px solid var(--color-border-tertiary)", borderRadius: "var(--border-radius-lg)", padding: "1rem 1.25rem", marginBottom: 10, cursor: "pointer" }}
              onClick={function() { setSelectedEntry(entry); setView("historyDetail"); }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
                <div>
                  <div style={{ fontSize: 15, fontWeight: 500, color: "var(--color-text-primary)", marginBottom: 4 }}>{entry.machineName}</div>
                  <div style={{ fontSize: 13, color: "var(--color-text-secondary)" }}>
                    {new Date(entry.startDate).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}
                    {" → "}
                    {new Date(entry.endDate).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}
                    {" · " + entry.weeks + " week" + (entry.weeks !== 1 ? "s" : "")}
                  </div>
                  <div style={{ display: "flex", gap: 8, marginTop: 6 }}>
                    <span style={{ fontSize: 12, background: "var(--color-background-secondary)", padding: "2px 8px", borderRadius: 4, color: "var(--color-text-secondary)" }}>
                      Total: {entry.totalHours}h
                    </span>
                    {entry.noWorkDays > 0 && (
                      <span style={{ fontSize: 12, background: "#FEE9E9", color: "#9B1C1C", padding: "2px 8px", borderRadius: 4 }}>
                        {entry.noWorkDays} no-work day{entry.noWorkDays !== 1 ? "s" : ""}
                      </span>
                    )}
                  </div>
                </div>
                <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 8 }}>
                  <span style={{ fontSize: 11, color: "var(--color-text-tertiary)" }}>Saved {savedStr}</span>
                  <button onClick={function(e) { e.stopPropagation(); deleteEntry(entry.id); }}
                    style={{ fontSize: 11, padding: "2px 8px", background: "transparent", color: "var(--color-text-tertiary)", border: "0.5px solid var(--color-border-tertiary)", borderRadius: 4, cursor: "pointer" }}>
                    Delete
                  </button>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    );
  }

  // ── HISTORY DETAIL ──
  if (view === "historyDetail" && selectedEntry) {
    return (
      <div style={{ padding: "1.5rem 1rem", maxWidth: 680, margin: "0 auto", fontFamily: "var(--font-sans)" }}>
        <NavBar />
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: "1.25rem" }}>
          <button onClick={function() { setView("history"); }} style={{ fontSize: 13, padding: "6px 12px" }}>← Back</button>
          <div>
            <div style={{ fontSize: 16, fontWeight: 500, color: "var(--color-text-primary)" }}>{selectedEntry.machineName}</div>
            <div style={{ fontSize: 12, color: "var(--color-text-secondary)" }}>
              {new Date(selectedEntry.startDate).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}
              {" → "}
              {new Date(selectedEntry.endDate).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}
              {" · Saved " + new Date(selectedEntry.savedAt).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}
            </div>
          </div>
        </div>
        <div style={{ background: "var(--color-background-primary)", border: "0.5px solid var(--color-border-tertiary)", borderRadius: "var(--border-radius-lg)", padding: "1.25rem" }}>
          <div style={{ display: "flex", gap: 10, marginBottom: "1rem" }}>
            {[
              { label: "Total Hours", value: selectedEntry.totalHours + "h" },
              { label: "Weeks", value: selectedEntry.weeks },
              { label: "No-Work Days", value: selectedEntry.noWorkDays },
            ].map(function(c, i) {
              return (
                <div key={i} style={{ flex: 1, background: "var(--color-background-secondary)", borderRadius: "var(--border-radius-md)", padding: "0.75rem" }}>
                  <div style={{ fontSize: 11, color: "var(--color-text-secondary)", marginBottom: 3 }}>{c.label}</div>
                  <div style={{ fontSize: 16, fontWeight: 500, color: "var(--color-text-primary)" }}>{c.value}</div>
                </div>
              );
            })}
          </div>
          <div style={{ fontSize: 14, lineHeight: 1.75, color: "var(--color-text-primary)" }}
            dangerouslySetInnerHTML={{ __html: renderMarkdown(selectedEntry.report) }} />
          <div style={{ marginTop: "1rem", paddingTop: "1rem", borderTop: "0.5px solid var(--color-border-tertiary)" }}>
            <DownloadButtons
              report={selectedEntry.report}
              machineName={selectedEntry.machineName}
              period={new Date(selectedEntry.startDate).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" }) + " – " + new Date(selectedEntry.endDate).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}
              totalHours={selectedEntry.totalHours}
              weeks={selectedEntry.weeks}
              noWorkDays={selectedEntry.noWorkDays}
            />
          </div>
        </div>
      </div>
    );
  }

  // ── HOME ──
  if (view === "home") {
    return (
      <div style={{ padding: "1.5rem 1rem", maxWidth: 680, margin: "0 auto", fontFamily: "var(--font-sans)" }}>
        <NavBar />
        <div style={{ textAlign: "center", padding: "2rem 0 1.5rem" }}>
          <div style={{ fontSize: 40, marginBottom: 12 }}>⚙</div>
          <h1 style={{ fontSize: 22, fontWeight: 600, margin: "0 0 0.5rem", color: "var(--color-text-primary)" }}>Machine Hours Tracker</h1>
          <p style={{ fontSize: 14, color: "var(--color-text-secondary)", margin: "0 0 1.5rem" }}>Track day and night shift odometer readings, calculate billed hours, and generate AI-powered weekly reports.</p>
          <div style={{ display: "flex", gap: 10, justifyContent: "center" }}>
            <button onClick={function() { setView("tracker"); setStep(1); }} style={{ padding: "10px 24px", fontWeight: 500, fontSize: 14 }}>+ New Report</button>
            {history.length > 0 && (
              <button onClick={function() { setView("history"); }} style={{ padding: "10px 24px", fontSize: 14 }}>View History ({history.length})</button>
            )}
          </div>
        </div>
        {history.length > 0 && (
          <div>
            <p style={{ fontSize: 13, fontWeight: 500, color: "var(--color-text-secondary)", margin: "1.5rem 0 0.75rem" }}>Recent reports</p>
            {history.slice(0, 3).map(function(entry) {
              return (
                <div key={entry.id} style={{ background: "var(--color-background-primary)", border: "0.5px solid var(--color-border-tertiary)", borderRadius: "var(--border-radius-lg)", padding: "0.875rem 1.25rem", marginBottom: 8, cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center" }}
                  onClick={function() { setSelectedEntry(entry); setView("historyDetail"); }}>
                  <div>
                    <div style={{ fontSize: 14, fontWeight: 500, color: "var(--color-text-primary)" }}>{entry.machineName}</div>
                    <div style={{ fontSize: 12, color: "var(--color-text-secondary)" }}>
                      {new Date(entry.startDate).toLocaleDateString("en-GB", { day: "numeric", month: "short" })} — {new Date(entry.endDate).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}
                      {" · " + entry.totalHours + "h total"}
                    </div>
                  </div>
                  <span style={{ fontSize: 13, color: "var(--color-text-tertiary)" }}>→</span>
                </div>
              );
            })}
          </div>
        )}
      </div>
    );
  }

  // ── TRACKER ──
  return (
    <div style={{ padding: "1.5rem 1rem", maxWidth: 700, margin: "0 auto", fontFamily: "var(--font-sans)" }}>
      <NavBar />

      {step === 1 && (
        <div style={{ maxWidth: 480, margin: "0 auto" }}>
          <h2 style={{ fontSize: 18, fontWeight: 500, margin: "0 0 0.25rem", color: "var(--color-text-primary)" }}>New Report</h2>
          <p style={{ fontSize: 14, color: "var(--color-text-secondary)", margin: "0 0 1.5rem" }}>Enter the machine details and working period.</p>
          <div style={{ background: "var(--color-background-primary)", border: "0.5px solid var(--color-border-tertiary)", borderRadius: "var(--border-radius-lg)", padding: "1.25rem" }}>
            <label style={{ fontSize: 13, color: "var(--color-text-secondary)", display: "block", marginBottom: 6 }}>Machine name / ID</label>
            <input type="text" placeholder="e.g. Excavator #7" value={machineName}
              onChange={function(e) { setMachineName(e.target.value); }}
              style={{ width: "100%", boxSizing: "border-box", marginBottom: "1.25rem" }} />
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginBottom: "1.25rem" }}>
              <div>
                <label style={{ fontSize: 13, color: "var(--color-text-secondary)", display: "block", marginBottom: 6 }}>Start date</label>
                <input type="date" value={startDate} onChange={function(e) { setStartDate(e.target.value); }} style={{ width: "100%", boxSizing: "border-box" }} />
              </div>
              <div>
                <label style={{ fontSize: 13, color: "var(--color-text-secondary)", display: "block", marginBottom: 6 }}>End date</label>
                <input type="date" value={endDate} onChange={function(e) { setEndDate(e.target.value); }}
                  style={{ width: "100%", boxSizing: "border-box", borderColor: dateError ? "var(--color-border-danger)" : undefined }} />
              </div>
            </div>
            {dateError && <p style={{ fontSize: 12, color: "var(--color-text-danger)", margin: "-8px 0 12px" }}>{dateError}</p>}
            {tooMany && <p style={{ fontSize: 12, color: "var(--color-text-danger)", margin: "-8px 0 12px" }}>Please select 31 days or fewer.</p>}
            {(dayCount > 0 && !tooMany && !dateError) && (
              <div style={{ background: "var(--color-background-secondary)", borderRadius: "var(--border-radius-md)", padding: "10px 12px", marginBottom: "1.25rem", fontSize: 13, color: "var(--color-text-secondary)" }}>
                {"📅 "}
                <strong style={{ color: "var(--color-text-primary)" }}>{dayCount} day{dayCount > 1 ? "s" : ""}</strong>
                {" (" + Math.ceil(dayCount / 6) + " week" + (Math.ceil(dayCount / 6) > 1 ? "s" : "") + ") — "}
                {new Date(startDate).toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "short" })}
                {" to "}
                {new Date(endDate).toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "short" })}
              </div>
            )}
            <button onClick={handleProceed} disabled={!startDate || !endDate || !!dateError || tooMany || dayCount === 0}
              style={{ width: "100%", padding: "10px", fontWeight: 500, fontSize: 14 }}>
              Continue → Enter odometer readings
            </button>
          </div>
        </div>
      )}

      {step === 2 && (
        <>
          <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: "1.25rem" }}>
            <div>
              <h2 style={{ fontSize: 18, fontWeight: 500, margin: "0 0 0.25rem", color: "var(--color-text-primary)" }}>{machineName || "Unnamed Machine"}</h2>
              <p style={{ fontSize: 13, color: "var(--color-text-secondary)", margin: 0 }}>
                {new Date(startDate).toLocaleDateString("en-GB", { weekday: "short", day: "numeric", month: "short", year: "numeric" })}
                {" → "}
                {new Date(endDate).toLocaleDateString("en-GB", { weekday: "short", day: "numeric", month: "short", year: "numeric" })}
                {" · " + days.length + " days · " + Math.ceil(days.length / 6) + " week" + (Math.ceil(days.length / 6) > 1 ? "s" : "")}
              </p>
            </div>
            <button onClick={function() { setStep(1); setSubmitted(false); setReport(""); }} style={{ fontSize: 13, padding: "6px 12px" }}>← Change period</button>
          </div>

          <div style={{ background: "var(--color-background-primary)", border: "0.5px solid var(--color-border-tertiary)", borderRadius: "var(--border-radius-lg)", padding: "1.25rem", marginBottom: "1.25rem" }}>
            <div style={{ display: "grid", gridTemplateColumns: "80px 1fr 1fr 12px 1fr 1fr 90px", gap: "4px 8px", marginBottom: 8 }}>
              <span />
              <span style={{ fontSize: 11, color: "#A0752B", textAlign: "center", background: "#FDF3E1", borderRadius: 4, padding: "2px 0" }}>☀ Day start</span>
              <span style={{ fontSize: 11, color: "#A0752B", textAlign: "center", background: "#FDF3E1", borderRadius: 4, padding: "2px 0" }}>☀ Day end</span>
              <span />
              <span style={{ fontSize: 11, color: "#4640A0", textAlign: "center", background: "#EEEDFE", borderRadius: 4, padding: "2px 0" }}>☾ Night start</span>
              <span style={{ fontSize: 11, color: "#4640A0", textAlign: "center", background: "#EEEDFE", borderRadius: 4, padding: "2px 0" }}>☾ Night end</span>
              <span style={{ fontSize: 11, color: "var(--color-text-tertiary)", textAlign: "right" }}>Total</span>
            </div>

            {rows.map(function(r, i) {
              const dh = dayHours[i], nh = nightHours[i], tot = totalPerDay[i];
              const db = dayBilled[i], nb = nightBilled[i];
              const dErr = hasErr(i, "day"), nErr = hasErr(i, "night");
              const d = days[i];
              const isWeekend = d.getDay() === 0 || d.getDay() === 6;
              const isNewWeek = i > 0 && i % 6 === 0;
              return (
                <div key={i} style={{ marginBottom: 10, paddingTop: i > 0 ? 8 : 0, borderTop: isNewWeek ? "2px solid var(--color-border-secondary)" : i > 0 ? "0.5px solid var(--color-border-tertiary)" : "none" }}>
                  {(i === 0 || isNewWeek) && (
                    <div style={{ fontSize: 11, fontWeight: 600, color: "var(--color-text-tertiary)", marginBottom: 6, letterSpacing: "0.05em" }}>
                      {"WEEK " + (Math.floor(i / 6) + 1)}
                    </div>
                  )}
                  <div style={{ display: "grid", gridTemplateColumns: "80px 1fr 1fr 12px 1fr 1fr 90px", gap: "4px 8px", alignItems: "center" }}>
                    <div>
                      <div style={{ fontSize: 13, fontWeight: 500, color: isWeekend ? "var(--color-text-secondary)" : "var(--color-text-primary)" }}>{DAY_NAMES[d.getDay()]}</div>
                      <div style={{ fontSize: 11, color: "var(--color-text-tertiary)" }}>{fmtDate(d, { day: "numeric", month: "short" })}</div>
                    </div>
                    {r.noWork ? (
                      <div style={{ gridColumn: "2 / 7", display: "flex", alignItems: "center", gap: 8 }}>
                        <span style={{ fontSize: 12, background: "#FEE9E9", color: "#9B1C1C", padding: "2px 8px", borderRadius: 4, fontWeight: 500, whiteSpace: "nowrap" }}>No Work</span>
                        <input type="text" placeholder="Reason (e.g. breakdown, holiday...)" value={r.reason}
                          onChange={function(e) { setReason(i, e.target.value); }}
                          style={{ flex: 1, fontSize: 13, boxSizing: "border-box" }} />
                      </div>
                    ) : (
                      <>
                        <input type="text" inputMode="decimal" placeholder="0.0" value={r.dayStart} onChange={function(e) { setField(i, "dayStart", e.target.value); }} style={inputSm(dErr)} />
                        <input type="text" inputMode="decimal" placeholder="0.0" value={r.dayEnd} onChange={function(e) { setField(i, "dayEnd", e.target.value); }} style={inputSm(dErr)} />
                        <div style={{ width: 1, background: "var(--color-border-tertiary)", height: 28, margin: "0 auto" }} />
                        <input type="text" inputMode="decimal" placeholder="0.0" value={r.nightStart} onChange={function(e) { setField(i, "nightStart", e.target.value); }} style={inputSm(nErr)} />
                        <input type="text" inputMode="decimal" placeholder="0.0" value={r.nightEnd} onChange={function(e) { setField(i, "nightEnd", e.target.value); }} style={inputSm(nErr)} />
                      </>
                    )}
                    <div style={{ textAlign: "right" }}>
                      {r.noWork ? <span style={{ fontSize: 11, color: "#9B1C1C" }}>—</span>
                        : (dErr || nErr) ? <span style={{ fontSize: 11, color: "var(--color-text-danger)" }}>error</span>
                        : tot !== null ? <span style={{ fontSize: 13, fontWeight: 500 }}>{fmt(tot)}</span>
                        : <span style={{ fontSize: 13, color: "var(--color-text-tertiary)" }}>—</span>}
                    </div>
                  </div>
                  <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: 4 }}>
                    {!r.noWork ? (
                      <div style={{ display: "grid", gridTemplateColumns: "80px 1fr 1fr 12px 1fr 1fr 90px", gap: "2px 8px", flex: 1 }}>
                        <span />
                        <span style={{ gridColumn: "2 / 4", fontSize: 11, color: dErr ? "var(--color-text-danger)" : "var(--color-text-tertiary)", paddingLeft: 2 }}>
                          {dErr ? "end < start" : dh !== null ? ("= " + fmt(dh) + " / billed " + db + "h") : ""}
                        </span>
                        <span />
                        <span style={{ gridColumn: "5 / 7", fontSize: 11, color: nErr ? "var(--color-text-danger)" : "var(--color-text-tertiary)", paddingLeft: 2 }}>
                          {nErr ? "end < start" : nh !== null ? ("= " + fmt(nh) + " / billed " + nb + "h") : ""}
                        </span>
                        <span />
                      </div>
                    ) : <div style={{ flex: 1 }} />}
                    <button onClick={function() { toggleNoWork(i); }}
                      style={{ fontSize: 11, padding: "2px 8px", marginLeft: 8, background: r.noWork ? "#FEE9E9" : "var(--color-background-secondary)", color: r.noWork ? "#9B1C1C" : "var(--color-text-secondary)", border: "0.5px solid " + (r.noWork ? "#FECACA" : "var(--color-border-tertiary)"), borderRadius: 4, cursor: "pointer", whiteSpace: "nowrap" }}>
                      {r.noWork ? "Undo" : "No work"}
                    </button>
                  </div>
                </div>
              );
            })}

            <div style={{ display: "flex", gap: 10, marginTop: "1.25rem" }}>
              <button onClick={generateReport} disabled={!canGenerate || loading} style={{ flex: 1, padding: "10px", fontWeight: 500, fontSize: 14 }}>
                {loading ? "Generating report..." : "Generate AI report ↗"}
              </button>
              <button onClick={function() { setRows(days.map(emptyRow)); setReport(""); setSubmitted(false); }} style={{ padding: "10px 16px", fontSize: 14 }}>Reset</button>
            </div>
            {!canGenerate && <p style={{ fontSize: 12, color: "var(--color-text-tertiary)", margin: "8px 0 0" }}>Enter at least one day's readings to generate a report.</p>}
          </div>

          {submitted && filledDays.length > 0 && (
            <div style={{ marginBottom: "1.25rem" }}>
              <div style={{ background: "var(--color-background-primary)", border: "0.5px solid var(--color-border-tertiary)", borderRadius: "var(--border-radius-lg)", padding: "1.25rem", marginBottom: "1.25rem" }}>
                <p style={{ fontSize: 13, fontWeight: 500, color: "var(--color-text-secondary)", margin: "0 0 1rem" }}>Daily hours breakdown</p>
                <div style={{ display: "flex", alignItems: "flex-end", gap: days.length > 14 ? 4 : 8, height: 140 }}>
                  {totalPerDay.map(function(tot, i) {
                    const dh = dayHours[i] || 0, nh = nightHours[i] || 0, t = tot || 0;
                    const pct = maxBar > 0 ? (t / maxBar) * 100 : 0;
                    const dPct = t > 0 ? (dh / t) * 100 : 50;
                    const isNoWork = rows[i].noWork;
                    return (
                      <div key={i} style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", height: "100%", justifyContent: "flex-end" }}>
                        {days.length <= 14 && <span style={{ fontSize: 10, color: "var(--color-text-secondary)", marginBottom: 3 }}>{isNoWork ? "—" : t > 0 ? t.toFixed(1) : ""}</span>}
                        <div style={{ width: "100%", height: Math.max(isNoWork ? 8 : pct, 2) + "%", borderRadius: "3px 3px 0 0", overflow: "hidden", background: isNoWork ? "#FEE9E9" : t === 0 ? "var(--color-border-tertiary)" : undefined }}>
                          {(!isNoWork && t > 0) && (
                            <>
                              <div style={{ width: "100%", height: dPct + "%", background: "#EF9F27" }} />
                              <div style={{ width: "100%", height: (100 - dPct) + "%", background: "#534AB7" }} />
                            </>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
                <div style={{ display: "flex", gap: days.length > 14 ? 4 : 8, marginTop: 6 }}>
                  {days.map(function(d, i) {
                    return <div key={i} style={{ flex: 1, textAlign: "center", fontSize: days.length > 14 ? 9 : 11, color: "var(--color-text-secondary)" }}>{days.length > 14 ? d.getDate() : DAY_NAMES[d.getDay()]}</div>;
                  })}
                </div>
                <div style={{ display: "flex", gap: 16, marginTop: 10 }}>
                  {[["#EF9F27", "Day shift"], ["#534AB7", "Night shift"], ["#FEE9E9", "No work"]].map(function(item) {
                    return (
                      <span key={item[1]} style={{ display: "flex", alignItems: "center", gap: 5, fontSize: 12, color: "var(--color-text-secondary)" }}>
                        <span style={{ width: 10, height: 10, borderRadius: 2, background: item[0], border: "0.5px solid var(--color-border-tertiary)", display: "inline-block" }} />{item[1]}
                      </span>
                    );
                  })}
                </div>
              </div>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(4, minmax(0,1fr))", gap: 10 }}>
                {[
                  { label: "Period total", value: fmt(grandTotal) },
                  { label: "Daily average", value: fmt(avg) },
                  { label: "Peak day", value: peakDayLabel + " · " + fmt(peak) },
                  { label: "No-work days", value: rows.filter(function(r) { return r.noWork; }).length + " day" + (rows.filter(function(r) { return r.noWork; }).length !== 1 ? "s" : "") },
                ].map(function(c, i) {
                  return (
                    <div key={i} style={{ background: "var(--color-background-secondary)", borderRadius: "var(--border-radius-md)", padding: "0.875rem 0.75rem" }}>
                      <div style={{ fontSize: 12, color: "var(--color-text-secondary)", marginBottom: 4 }}>{c.label}</div>
                      <div style={{ fontSize: 14, fontWeight: 500, color: "var(--color-text-primary)" }}>{c.value}</div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {(loading || report || error) && (
            <div ref={reportRef} style={{ background: "var(--color-background-primary)", border: "0.5px solid var(--color-border-tertiary)", borderRadius: "var(--border-radius-lg)", padding: "1.25rem" }}>
              <p style={{ fontSize: 13, fontWeight: 500, color: "var(--color-text-secondary)", margin: "0 0 0.75rem" }}>
                {"AI-generated report — " + (machineName || "Unnamed Machine")}
              </p>
              {loading && (
                <div style={{ display: "flex", alignItems: "center", gap: 10, color: "var(--color-text-secondary)", fontSize: 14 }}>
                  <span style={{ display: "inline-block", width: 14, height: 14, border: "2px solid var(--color-border-secondary)", borderTopColor: "var(--color-text-secondary)", borderRadius: "50%", animation: "spin 0.8s linear infinite" }} />
                  Analyzing data...
                </div>
              )}
              {error && <p style={{ color: "var(--color-text-danger)", fontSize: 14 }}>{error}</p>}
              {report && (
                <div>
                  <div style={{ fontSize: 14, lineHeight: 1.75, color: "var(--color-text-primary)" }} dangerouslySetInnerHTML={{ __html: renderMarkdown(report) }} />
                  <div style={{ marginTop: "1rem", paddingTop: "1rem", borderTop: "0.5px solid var(--color-border-tertiary)", display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center", justifyContent: "space-between" }}>
                    <DownloadButtons
                      report={report}
                      machineName={machineName || "Unnamed Machine"}
                      period={new Date(startDate).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" }) + " – " + new Date(endDate).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}
                      totalHours={grandTotal.toFixed(2)}
                      weeks={Math.ceil(days.length / 6)}
                      noWorkDays={rows.filter(function(r) { return r.noWork; }).length}
                    />
                    <button onClick={function() { setView("history"); }} style={{ fontSize: 13, padding: "6px 14px" }}>View in History →</button>
                  </div>
                </div>
              )}
            </div>
          )}
        </>
      )}

      <style>{"@keyframes spin { to { transform: rotate(360deg); } }"}</style>
    </div>
  );
}